[package]
name = "rhdl-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
log = "0.4.20"
prettyplease = "0.2.15"
rhdl-bits = { path = "../rhdl-bits" }
serde = { version = "^1", features = ["derive"] }
svg = { version = "0.14.0", optional = true }
syn = "2.0.38"

[features]
default = ["svg"]
svg = ["dep:svg"]
