[package]
name = "rhdl-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
rhdl-bits = { path = "../rhdl-bits" }
serde = { version = "^1", features = ["derive"] }
svg = { version = "0.14.0", optional = true }

[features]
default = ["svg"]
svg = ["dep:svg"]
