[workspace]

[package]
name = "rhdl-x"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
const-fnv1a-hash = "1.1.0"
fnv = "1.0.7"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
